spring:
    application:
        name: RecipeRealmOreshcode
    datasource:
        url: jdbc:mysql://localhost:3306/Recipe_Realm_Oreshcode?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        format-sql: true

spring-doc:
    api-docs:
        path=/api-docs:
jwt:
    token-validity: '3600000'
    secret: ZTRiNmI1Y2I3MWUxYmFmODNiYmIwYjMzYzhhMDM3NjYzODI0MTgzYmY2Yjg5MThlMGVkYmQxMTQ3MGVkNWUwZTMyM2QzM2I3Njk4MDk1NmRlOGVjOTQ0YWFhZGVhZWQ3OWM5ZDJjMzllYzQ1ZmNhNWMzY2IwYmRkNzVkNjMxZjY=
